### ISSUE TITLE
Core vs non-core conflict and solutions to enhance the module and plugin systems

### ISSUE THREAD

**Issue by Xrayez** [godot-extended-libraries/godot-ideas#9]
## Context
There's been an on-going discussion over the [godot-proposals](https://github.com/godotengine/godot-proposals) process (GIP) and how it possibly conflicts with user expectations. Here's Godot's current mission/ideology:

https://github.com/godotengine/godot-proposals/issues/47#issuecomment-533886764

> Our mission is about making something useful for others based on their real needs, not having fun adding features that we find cool, that no one currently needs, so that may nor may not be useful.

Also see: 
* Problems with preventing "engine bloat" and the AssetLibrary godotengine/godot#19486.

### Sides of conflict

Strictly speaking, we have two camps:

1. Engine core developers which aim to keep Godot as minimal as possible:

    https://github.com/godotengine/godot-proposals/issues/10#issuecomment-527863971

    > The problem is that the amount of content in this regard submitted daily is enormous, and it is only going to **get worse**. [emphasis mine]

     The reasons are mainly maintenance burden and engine binary size (for instance, to keep it small to be available for mobile devices).

2. Godot users/developers/hobbyists which expect the engine to provide a lot of life-improvement and some game-specific features, whether they are needed or not by majority is irrelevant to them:

    https://github.com/godotengine/godot-proposals/issues/10#issuecomment-527830874
    > I am concerned this process will further diminish involvement of users who are not contributors themselves or much involved in the community but just USE the engine for their purposes (aka by far the vast majority of Godot users).

### Result of conflict
These camps of course create an unwanted split:

https://github.com/godotengine/godot-proposals/issues/10#issuecomment-532357516
> I find this problematic and very much contradicting the idea of Godot being community driven if this community is split in two.

https://github.com/godotengine/godot-proposals/issues/47#issuecomment-531621673
> I honestly believe more separating at this point is just not a good idea, we need more centralization!

---

Users should not spent a considerable amount of time seeking for existing, somewhat common solutions to their tasks (especially for non-programmers), like extended debugging tools or utility methods which can ease the development process.

So what could be the solution to resolve this conflict (if ever)? 😅 

## Suggestion

There could be many ways to solve the conflict, and they can only enhance each other:

1. Improve module/plugin ecosystem so that the process of extending Godot is more seamless:

    https://github.com/godotengine/godot-proposals/issues/47#issuecomment-529934213
    > Along with that I think there is potential for the more techy guys to streamline the solution for the rest of us for building GDnative and perhaps modules for different platforms. It should ideally be as easy to get something available via non-core as it is through core (or, even easier because the review process can be less stringent).

2. Create an extended version of Godot (maintained either by core or independent developers) which adds upon existing engine via plugins that prove to be useful by at least 10-20% of the people using Godot (without the burden of visiting the AssetLib and installing half-baked solutions and hope that they work).

Improving/implementing either of these could also help to determine what actually could be considered to be included as part of the engine core while users test these features.

## Solution

Define "packages" or "framework profiles" that would just be a named collection of other addons/plugins/assets. https://github.com/godot-extended-libraries/godot-ideas/issues/9#issuecomment-537094980

Proposals listed in #6 might be good candidates for "full-pack" version of Godot, because they were already targeted to be reviewed by core developers at godot-proposals. Other ideas presented in this repository that received a lot of feedback could also be implemented to cater more needs. I say "needs" because the "want" is seen as "need" here.

## Conclusion
https://github.com/godotengine/godot-proposals/issues/47#issuecomment-533880718

> The hard line of conflict will probably always be the dismissal of proposals that don't have user interest, or any practical use in existing projects (even if they sound cool), and this won't change because we want to avoid bloating Godot with stuff no one will use.

https://github.com/godotengine/godot-proposals/issues/100#issuecomment-535914894

> It's an ever-going battle, finding the right balance can't content everyone :p

**Comment by willnationsdev** [comment]
Between the two, I would much prefer opting for suggestion 1 (which is also the approach that the core devs favor, for similar reasons) because creating and maintaining a separate "packed" version of Godot would ultimately be a *whole* bunch of work. Too much work to keep up with imo.

If you focus on improving the workflow of importing plugins, handling their dependencies somehow, and/or creating a Godot module manager that can download and install engine modules and build the source code for users, then there would be a lot less hassle in working with non-core code.

**Comment by lawnjelly** [comment]
I can't comment on GDNative yet as I haven't tried it, but I would say that one of the biggest differences between relying on GDNative / addons and having an extended version of Godot is the matter of version control.

### Version control in Core
This is already quite problematic if we consider the core. Consider that each stable release of Godot (e.g. 3.1.1) might contain bugs that have been fixed in the latest master. Someone who is developing a game and hits a particular bug then has a choice:

1) Workaround / avoid that particular bug
2) Compile / download the latest master with fixes
3) Wait for the fix to be cherry picked and back ported to the stable version

The problem with (2) is that as every bug is fixed in master, new bugs are introduced. So you are left in a situation where you are trading old bugs for new bugs. (3) would be the best, except that it can be labour intensive and a lot of work for Akien - and some fixes are easier to backport than others.

### Version control in extensions
The more features you start adding (e.g. with all these extensions), the surface area for bugs increases exponentially. This is one of the reasons for keeping the core as small as possible. It would be effectively impossible to keep a load of extensions maintained by different people relatively bug free, but it is theoretically possible to keep the number of bad bugs in core under control (whether this is achieved is another thing! :smile: ).

Although I agree that creating an extended version of Godot is a good potential option, consider that the version controlling is something that would need to be thought through. Would all the extensions be required to work to the previous latest stable version of the core, or would it be based on the latest master core (and hence have the problem mentioned above)?

You could end up in a situation where a user is using 2 extensions, 1 extension has a bug which is fixed in the latest version (which you need) and the other extension has added new features in the meantime and introduced new bugs which break your build. So you want a combination of different feature sets, but it is not available with the one size fits all approach. As such it would need a certain amount of restraint by extension contributors as to which version they provided for builds.

### Keeping core small
I actually think this issue of bug surface area and version control is probably more important in practice than the idea of 'saving RAM' and download size for smaller devices. Even mobile phones have shedloads of memory these days, so it is more download size if anything that might be an issue. And if extensions are designed sensibly they shouldn't bloat the executable size. Well, I say that, but I don't know how expensive each module is in terms of size. Would be worth investigating.

I also agree with willnationdev that although an extended build is easier *now*, ultimately, making things easier for developers to make / distribute plugins is probably the best option.

**Comment by willnationsdev** [comment]
I imagine we would get to a point where people can start defining "packages" or "framework profiles" that would just be a named collection of other addons/plugins/assets that are all versioned. End-users could then just install the vanilla engine, go to the Asset Lib, and specify a popular framework profile, and it would immediately download a big collection of tools and scripts that make building those types of games a lot easier. Will probably submit an actual proposal for that in the near future.

**Comment by Xrayez** [comment]
I just realized that this continues godotengine/godot#19486, but looking from the perspective of already discussed ideas and opinions at godot-proposals. Indeed there could be many solutions to this. 🙂 

---

> 2. Compile / download the latest master with fixes

I think this option is best if:

* you're working on a long term project.
* don't plan to release anything yet, so bugs aren't too catastrophic.

If you do release something, you better stick to stable version indeed.

> You could end up in a situation where a user is using 2 extensions, 1 extension has a bug which is fixed in the latest version (which you need) and the other extension has added new features in the meantime and introduced new bugs which break your build.

Happened to me several times while on master, I just had to include my temporary manual patch for the plugin. Unfortunately not a lot of devs are basing their work against master branch.

**Comment by Xrayez** [comment]
> I imagine we would get to a point where people can start defining "packages" or "framework profiles" that would just be a named collection of other addons/plugins/assets that are all versioned.

That still requires some magical work to be done by less-experienced users. The idea behind an extended engine version is ease of use, out-of-the-box experience. Of course none of the core developers would go for this step, so it's up for community (and I'm not saying that Godot engine members are not part of community, Akien!) 🙂

**Comment by willnationsdev** [comment]
@Xrayez 

> That still requires some magical work to be done by less-experienced users.

That depends on the UX. If, say, we modified the Project Manager to let people select framework profiles to add to their project upon creation, perhaps as a sidebar with a mini-explanation of the available frameworks, then people would more readily use and install them, and their project would immediately get setup the moment the it is created (making for an out-of-the-box experience).

And I think that something like this is *exactly* the kind of thing the core devs would support since it's about improving the core engine's ability to install and maintain third party asset/addons/plugins. Their end goal is to create a vibrant asset library and the ease of use of installing and using those things to have an engine/editor tailor-made for different types of games is *exactly* the kind of thing that would fit their target goal.

**Comment by RaTcHeT302** [comment]
man, if it was me i would focus on the vulkan release at this point, i think godot is trying to tackle too many problems at once, it feels like the project is really disorganized currently, i feel like some of the focus has been lost

honestly, the people who are making actual games, should just re-compile the engine, with whatever fixes they need, temporarily at least 

i think the workload is too high, and i feel like the developers could lend a hand by themselves, by just manually merging whatever fixes currently exist, into their games

man the whole thing is just a mess, i really got no clue, beyond just going forward really
i wish i had something more to say

personally it would feel wrong for me if i had to update multiple versions of the same engine over and over again, i would much rather focus on the real deal, i really don't think there's any other solution currently, beyond focusing on the future version of the engine

working with the old stuff just seems like a complete waste of time, in the end, i think there's straght up too much work to do, and i would rather just have one good release, instead of three half assed ones, even if it ends up screwing over a couple of people

**Comment by willnationsdev** [comment]
@RaTcHeT302 

I'm not sure what your experience has been with open-source projects, but from what I've observed with Godot, and what I've been told my akien, reduz, and other contributors is that, because people work on a volunteer basis and contribute to whatever it is they want to contribute to, the fact that many different things might be going on at once isn't an indication of unclear focus, but rather just a by-product of people working on what they are interested in.

For example, I have no interest in rendering code or vulkan, even if I might like to take advantage of others' work one day. My personal primary interest is in improving the scripting language support, the addon ecosystem, and the editor usability, all so that I can get to the business of building community tools/plugins/frameworks and get to building games after that.

But just because I personally open proposals and get people talking about those topics occasionally, it doesn't mean that the engine's overall focus is there. The majority of people are just getting ready for the 3.2 release right now (and it's been almost a year since the last release, iirc, so it's a good time).

There are no real plans to start simultaneously developing multiple bundles of the same version of engine release. I think the best way to solve the problems stated in the OP is...

1. Revamp the Godot Asset Library to track asset versions, not assets (for which there is an Issue).
    - @Calinou, iirc, is at work refactoring the Asset Library to use a new web framework and afaik implementing versioned assets is on the to-do list as part of that revision.
1. Implement a mechanism for tree-like project/addon relationships with dependency management. I believe the most popular suggestion for this thus far is reduz's godotengine/godot Issue about being able to use a project as a sub-project. That way, addons/plugins are absolved altogether of responsibility for packaging things and you instead use projects alone. Definitely some kinks to work out with that idea though.
1. Implement a mechanism for script classes, i.e. globally named scripts, to have namespaces in the engine. For this, languages need to be able to define fully namespaced names AND import namespaces. GDScript currently has no notion of these ideas.

All of this together would suddenly make it possible for people to upload things they want conveniently (first step), download things other people have shared painlessly (second step), and share content with others without worrying about naming conflicts (third step). All that together should get things moving more quickly in the community. I see that happening with maybe version 4.0 or 4.1.

I'm planning to get all scripting languages to have script class support by 4.0.

**Comment by Xrayez** [comment]
Closing as being silly, just wanted to sum it up really. Feel free to discuss this though.

Also I've opened a "proposal" which aims to discuss more fundamental principles of Godot development in general: godotengine/godot-proposals#575.
